name: deploy to production
on:
  push:
    branches:
      - 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout V2"
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Tag Staging Version
      run: |
        echo "Working on branch ${{ github.ref }}"
    - name: Enforce Commit Message Format
      run: |
        echo "Consider to put the validation on create pull request"

      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.VANTI_ADMIN_GITHUN_TOKEN }}
        branch: main
        repository: "hammock-studio/git-flow-example-"
        force: true