name: deploy to production
on:
  push:
    branches:
      - 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Tag Staging Version
      run: |
        echo "Working on branch ${{ github.ref }}"
        latest_version=$(git tag | sort -V | tail -1)
        latest_version_major=$(echo $latest_version | cut -c2-2)
        latest_version_minor=$(echo $latest_version | cut -c4-4)
        echo "Latest Version: v${latest_version_major}.${latest_version_minor}"

        let new_version_minor=latest_version_minor+1
        new_version="v${latest_version_major}.${new_version_minor}"
        echo "About to Tag ${new_version}"
        git config --global user.name ${{ secrets.NAME }}
        git config --global user.email ${{ secrets.EMAIL }}
        git tag -a ${new_version} -m ${new_version}
      
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.VANTI_ADMIN_GITHUN_TOKEN }}
          branch: staging
          repository: "hammock-studio/git-flow-example-"
          tags: true

    - name: Enforce Commit Message Format
      run: |
        echo "Consider to put the validation on create pull request"
        echo "Enforce single commit message in order to deploy"
    - name: Run e2e Tests
    - run: |
        echo "Run e2e test send default success() for testing"
        echo "Consider writing the e2e trigger as component"
    - name: Deploy To Staging
    - run:
        echo "Invode ECR + ECS deployment"
