name: deploy to production
on:
  push:
    branches:
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Commit files
      run: |
        git fetch
        git checkout staging
        git reset --hard origin/staging
        git checkout main
        git reset --hard origin/main
        git rebase staging
        
    - name: Validate context ref
      run:
        echo "this is change in ${{ github.ref }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.VANTI_ADMIN_GITHUN_TOKEN }}
        branch: main
        repository: "hammock-studio/git-flow-example-"
        force: true